apiVersion: apps/v1
kind: Deployment
metadata:
        name: comments
spec:
        selector:
                matchLabels:
                        app: comments
        template:
                metadata:
                        labels:
                                app: comments
                spec:
                        containers:
                                - name: comments
                                  image: heaty566/comments
---
apiVersion: v1
kind: Service
metadata:
        name: comment-clusterip-srv
spec:
        selector:
                app: comments
        ports:
                - name: comments
                  protocol: TCP
                  port: 4001
                  targetPort: 4001
