apiVersion: apps/v1
kind: Deployment
metadata:
        name: moderation
spec:
        selector:
                matchLabels:
                        app: moderation
        template:
                metadata:
                        labels:
                                app: moderation
                spec:
                        containers:
                                - name: moderation
                                  image: heaty566/moderation
---
apiVersion: v1
kind: Service
metadata:
        name: moderation-clusterip-srv
spec:
        selector:
                app: moderation
        ports:
                - port: 4003
                  targetPort: 4003
