apiVersion: apps/v1
kind: Deployment
metadata:
        name: query
spec:
        selector:
                matchLabels:
                        app: query
        template:
                metadata:
                        labels:
                                app: query
                spec:
                        containers:
                                - name: query
                                  image: heaty566/query
---
apiVersion: v1
kind: Service
metadata:
        name: query-clusterip-srv
spec:
        selector:
                app: query
        ports:
                - port: 4002
                  targetPort: 4002
